// <auto-generated />
using System;
using AssessmentPreparation.Repositories.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssessmentPreparation.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("AssessmentPreparation.Common.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("Date")
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2020, 7, 2, 14, 32, 34, 727, DateTimeKind.Local).AddTicks(5512));

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Board #1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Board #2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Board #3"
                        });
                });

            modelBuilder.Entity("AssessmentPreparation.Common.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("Date")
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2020, 7, 2, 14, 32, 34, 724, DateTimeKind.Local).AddTicks(5819));

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Random Description",
                            Title = "Random Title"
                        });
                });

            modelBuilder.Entity("AssessmentPreparation.Common.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 715, DateTimeKind.Local).AddTicks(3137),
                            Summary = "Freezing",
                            TemperatureC = 0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(731),
                            Summary = "Bracing",
                            TemperatureC = 5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(916),
                            Summary = "Chilly",
                            TemperatureC = 10
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(922),
                            Summary = "Cool",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(926),
                            Summary = "Mild",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(930),
                            Summary = "Warm",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(933),
                            Summary = "Balmy",
                            TemperatureC = 27
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(936),
                            Summary = "Hot",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(939),
                            Summary = "Sweltering",
                            TemperatureC = 35
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2020, 7, 2, 14, 32, 34, 719, DateTimeKind.Local).AddTicks(943),
                            Summary = "Scorching",
                            TemperatureC = 40
                        });
                });

            modelBuilder.Entity("AssessmentPreparation.Common.Models.Note", b =>
                {
                    b.HasOne("AssessmentPreparation.Common.Models.Board", "Board")
                        .WithMany("Notes")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
